---
- name: Configure Firewalld
  hosts: all
  vars_files:
    - firewall_rules.yml
    - ports.yml
  become: true
  tasks:
    - name: Install Firewalld (if not already installed)
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: Start Firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true

    - name: Load Firewalld rules
      ansible.posix.firewalld:
        service: "{{ item.service }}"
        # port: "{{ item.port_number }}/{{ item.protocol }}"
        permanent: "{{ item.permanent }}"
        state: "{{ item.state }}"
      loop: "{{ rules }}"

    - name: Reload Firewalld
      ansible.builtin.command: firewall-cmd --reload
      register: output
      changed_when: false
